live_config_reload = true

[colors.bright]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xdcdfe4"

[font]
size = 12.5


[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Light"

[cursor]
style.shape = "Block"
style.blinking = "On"
unfocused_hollow = true
thickness = 0.15

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
option_as_alt = "Both"

[env]
TERM = "xterm-256color"

[[hints.enabled]]
action = "copy"
regex = "([0-9a-f]{40}([0-9a-f]{24})?)|([0-9a-f]{7,10})"

[hints.enabled.binding]
key = "S"
mods = "control"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
